matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: 3.6
      services:
        - docker
    - os: osx
      language: generic
      osx_image: xcode8.3

install:
  - git submodule update --remote
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then BUILD_NUMBER="$TRAVIS_BUILD_NUMBER" ./linux.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./osx.sh; fi

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#openteacher"
    use_notice: true
    skip_join: true

addons:
  ssh_known_hosts:
    - web.openteacher.org
    - git.launchpad.net
