sudo: requires

language: python
python:
  - "3.6"

os:
  - linux
  - osx
services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux "]]; then ./build.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./run.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./osx.sh; fi

deploy:
  skip_cleanup: true
