sudo: requires
language: python # but we don't actually use it, it's all docker

services:
  - docker

install:
  - docker build -t openteacher .

env:
  - ARGS=-p test-suite full
  - ARGS=-p code-complexity

script:
  - docker run openteacher $ARGS
