init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

build: off

test_script:
  - windows.bat

artifacts:
  - path: output
